/* ════════════════════════════════════════════════════════════════════════
   Curated list of US universities international F-1 applicants commonly
   target. Used by the onboarding "University" typeahead so students pick
   from a real name instead of free-typing (which produces typos that
   break downstream SEVIS/DS-160 cross-checks).

   Not exhaustive — "Other" always remains available as free text.
   ════════════════════════════════════════════════════════════════════════ */
export const US_UNIVERSITIES: string[] = [
  "Arizona State University",
  "Boston University",
  "Carnegie Mellon University",
  "Columbia University",
  "Cornell University",
  "Duke University",
  "George Washington University",
  "Georgia Institute of Technology",
  "Harvard University",
  "Illinois Institute of Technology",
  "Indiana University Bloomington",
  "Johns Hopkins University",
  "Massachusetts Institute of Technology",
  "New York University",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Penn State University",
  "Purdue University",
  "Rutgers University",
  "Stanford University",
  "Stevens Institute of Technology",
  "Syracuse University",
  "Texas A&M University",
  "University at Buffalo (SUNY)",
  "University of California, Berkeley",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Santa Barbara",
  "University of Chicago",
  "University of Cincinnati",
  "University of Florida",
  "University of Illinois Urbana-Champaign",
  "University of Maryland, College Park",
  "University of Massachusetts Amherst",
  "University of Michigan",
  "University of Minnesota",
  "University of North Carolina at Chapel Hill",
  "University of Pennsylvania",
  "University of Southern California",
  "University of Texas at Arlington",
  "University of Texas at Austin",
  "University of Texas at Dallas",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Virginia Tech",
  "Wayne State University",
  "Yale University",
];
